{% set name = "seekr2_openmm_plugin" %}
{% set version = "0.1.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/seekrcentral/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6deff2c0c3b6e3f1e7ed66dd30fb4bad34dafb62b4a8cac4e877add97122f4a6

# used command: shasum -a 256 seekr2_openmm_plugin-0.1.0.tar.gz

build:
  number: 1
  skip: true  # [win or osx or (linux64 and cuda_compiler_version == "None")]
  
requirements:
  build:
    - openmm
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux]
    - cmake

  host:
    - openmm
    - python
    - pip
    - fftw
    - swig
    - pthread-stubs
    - lxml
    #- {{ pin_compatible('numpy') }}
    - cython
    # needed for Python wrappers
    - doxygen 1.8.14
    # OpenCL ICD
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [osx or win]
    
  run:
    - python
    - fftw
    - openmm
    #- {{ pin_compatible('numpy') }}
    - swig
    - pthread-stubs
    # OpenCL ICD
    - khronos-opencl-icd-loader  # [osx or win]
    - ocl_icd_wrapper_apple  # [osx]
    - ocl-icd  # [linux]
    - ocl-icd-system  # [linux]

test:
  requires:
    - pocl  # [unix]
    - pip
  imports:
    - simtk
    - simtk.openmm
  commands:
#    - python -m simtk.testInstallation
#    # Existence tests Unix
    - pip check
    - test -f $PREFIX/lib/plugins/libSeekr2PluginCUDA$SHLIB_EXT  # [unix]
    - test -f $PREFIX/lib/plugins/libSeekr2PluginReference$SHLIB_EXT  # [unix]

about:
  home: https://github.com/seekrcentral/seekr2_openmm_plugin.git
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: An OpenMM plugin for SEEKR2.

  description: |
    Fast and versatile multiscale milestoning to compute molecular 
    thermodynamics and kinetics.
  doc_url: https://seekr2.readthedocs.io/en/latest/
  dev_url: https://github.com/seekrcentral/seekr2.git

extra:
  recipe-maintainers:
    - lvotapka
