{% set name = "seekr2_openmm_plugin" %}
{% set version = "0.1.5" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/seekrcentral/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: f292051f533b20dd97cd0e8ba7f55a9313f4a8591f8cdf31e278758f02a664cc

# used commands:
# wget https://github.com/seekrcentral/seekr2_openmm_plugin/archive/refs/tags/0.1.5.tar.gz
# shasum -a 256 0.1.5.tar.gz

build:
  number: {{ build }}
  skip: true  # [(win and py==310) or (cuda_compiler_version in (undefined, 'None') and (linux64 or win)) or ((cuda_compiler_version != '10.2') and (ppc64le))]
  script_env:
    - CONFIG
    - CUDA_HOME  # [ppc64le]
  missing_dso_whitelist:
    - "*/libcuda.*"    # [linux64 or ppc64le]
    - "*/libOpenCL.*"  # [unix]
    - "*/nvcuda.dll"   # [win]
  
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - swig                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 or ppc641le or win]
    - openmm
    - cmake
    - make
    - sysroot_linux-64 2.17  # [linux64]
    - doxygen
    - ocl-icd  # [linux]

  host:
    - openmm
    - python
    - pip
    - fftw
    - swig 4.0.2
    - pthread-stubs
    - lxml
    #- {{ pin_compatible('numpy') }}
    - cython
    # needed for Python wrappers
    - doxygen 1.8.14
    # OpenCL ICD
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [osx or win]
    
  run:
    - python
    - fftw
    - openmm
    #- {{ pin_compatible('numpy') }}
    - swig 4.0.2
    - pthread-stubs
    # OpenCL ICD
    - khronos-opencl-icd-loader  # [osx or win]
    - ocl_icd_wrapper_apple  # [osx]
    - ocl-icd  # [linux]
    - ocl-icd-system  # [linux]

test:
  requires:
    - pocl  # [unix]
    - pip
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}  # tests need nvcc
  imports:
    - openmm
    - seekr2plugin
  commands:
    - python -m openmm.testInstallation
#    # Existence tests Unix
    - pip check
    - test -f $PREFIX/lib/plugins/libSeekr2PluginCUDA$SHLIB_EXT  # [unix]
    - test -f $PREFIX/lib/plugins/libSeekr2PluginReference$SHLIB_EXT  # [unix]
    - export CUDA_VISIBLE_DEVICES=0
    - python -m seekr2plugin

about:
  home: https://github.com/seekrcentral/seekr2_openmm_plugin.git
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: An OpenMM plugin for SEEKR2.

  description: |
    Fast and versatile multiscale milestoning to compute molecular 
    thermodynamics and kinetics.
  doc_url: https://seekr2.readthedocs.io/en/latest/
  dev_url: https://github.com/seekrcentral/seekr2.git

extra:
  recipe-maintainers:
    - lvotapka
