{% set name = "seekr2_openmm_plugin" %}
{% set version = "0.1.9" %}
{% set build = 1 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/seekrcentral/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4ad94bc2dd03b01ab3e56d4659e0f74b620b444e8c3e56572dfe2c285a22521c

# used commands:
# wget https://github.com/seekrcentral/seekr2_openmm_plugin/archive/refs/tags/0.1.9.tar.gz
# shasum -a 256 0.1.9.tar.gz

build:
  number: {{ build }}
  skip: true  # [not linux64]
  skip: true  # [cuda_compiler_version == "None"]
  missing_dso_whitelist:
    - "*/libcuda.*"    # [linux64 or ppc64le]
    - "*/libOpenCL.*"  # [unix]
    - "*/nvcuda.dll"   # [win]
  
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - swig                                   # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
    - cmake
    - make
    - doxygen
    - ocl-icd  # [linux]
    
  host:
    - openmm
    - python
    - setuptools
    - pip
    - fftw
    - swig 4.0.2
    - pthread-stubs
    - lxml
    - cython
    # needed for Python wrappers
    - doxygen 1.8.14
    # OpenCL ICD
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [osx or win]
    
  run:
    - python
    - fftw
    - openmm
    - swig 4.0.2
    - pthread-stubs
    # OpenCL ICD
    - khronos-opencl-icd-loader  # [osx or win]
    - ocl_icd_wrapper_apple  # [osx]
    - ocl-icd  # [linux]
    - ocl-icd-system  # [linux]

test:
  requires:
    - pocl  # [unix]
    - pip
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}  # tests need nvcc
  imports:
    - openmm
    - seekr2plugin
  commands:
    - python -m openmm.testInstallation
#    # Existence tests Unix
    - pip check
    - test -f $PREFIX/lib/plugins/libSeekr2PluginCUDA$SHLIB_EXT  # [unix]
    - test -f $PREFIX/lib/plugins/libSeekr2PluginReference$SHLIB_EXT  # [unix]
    - export CUDA_VISIBLE_DEVICES=0
    - python -m seekr2plugin
    - python -c "import seekr2plugin; seekr2plugin.printKeyInformationDEBUG(); seekr2plugin.testSeekr2Plugin()"

about:
  home: https://github.com/seekrcentral/seekr2_openmm_plugin.git
  license: MIT AND LGPL-3.0-or-later
  license_file:
    - LICENSE
  summary: An OpenMM plugin for SEEKR2.

  description: |
    Fast and versatile multiscale milestoning to compute molecular 
    thermodynamics and kinetics.
  doc_url: https://seekr2.readthedocs.io/en/latest/
  dev_url: https://github.com/seekrcentral/seekr2.git

extra:
  recipe-maintainers:
    - lvotapka
