{% set name = "seekr2_openmm_plugin" %}
{% set version = "0.1.4" %}
{% set build = 2 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/seekrcentral/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6deff2c0c3b6e3f1e7ed66dd30fb4bad34dafb62b4a8cac4e877add97122f4a6

# used commands:
# wget https://github.com/seekrcentral/seekr2_openmm_plugin/archive/refs/tags/0.1.4.tar.gz
# shasum -a 256 0.1.4.tar.gz

build:
  number: {{ build }}
  skip: true  # [(win and py==310) or (cuda_compiler_version in (undefined, 'None') and (linux64 or win)) or ((cuda_compiler_version != '10.2') and (ppc64le))]
  script_env:
    - CONFIG
    - CUDA_HOME  # [ppc64le]
  
requirements:
  build:
    - openmm
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux]
    - cmake
    - sysroot_linux-64 2.17  # [linux64]

  host:
    - openmm
    - python
    - pip
    - fftw
    - swig 4.0.2
    - pthread-stubs
    - lxml
    #- {{ pin_compatible('numpy') }}
    - cython
    # needed for Python wrappers
    - doxygen 1.8.14
    # OpenCL ICD
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [osx or win]
    
  run:
    - python
    - fftw
    - openmm
    #- {{ pin_compatible('numpy') }}
    - swig 4.0.2
    - pthread-stubs
    # OpenCL ICD
    - khronos-opencl-icd-loader  # [osx or win]
    - ocl_icd_wrapper_apple  # [osx]
    - ocl-icd  # [linux]
    - ocl-icd-system  # [linux]

test:
  requires:
    - pocl  # [unix]
    - pip
  imports:
    - openmm
  commands:
    - python -m openmm.testInstallation
#    # Existence tests Unix
    - pip check
    - test -f $PREFIX/lib/plugins/libSeekr2PluginCUDA$SHLIB_EXT  # [unix]
    - test -f $PREFIX/lib/plugins/libSeekr2PluginReference$SHLIB_EXT  # [unix]
    - python -m seekr2plugin

about:
  home: https://github.com/seekrcentral/seekr2_openmm_plugin.git
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: An OpenMM plugin for SEEKR2.

  description: |
    Fast and versatile multiscale milestoning to compute molecular 
    thermodynamics and kinetics.
  doc_url: https://seekr2.readthedocs.io/en/latest/
  dev_url: https://github.com/seekrcentral/seekr2.git

extra:
  recipe-maintainers:
    - lvotapka
